apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin-demo
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: httpbin
